### PR TITLE
Fix a bug where objects' doSetup() functions could be called again after save/reload.

### LINKED ISSUE #113: Suggestion: change how `doSetup()` interacts with reloading saves [NI spoilers in description].
Proper automation of many of the NI aspects requires setup code, like for Sunshine and Immense. For the least spoilerific example: automation on Unconstrained Fangs to delete the starting beast in the player area. I've run into a problem while implementing this that isn't specific to NI content in particular, that I think could be addressed in the main mod.

The problem relates to `doSetup()` code when saving and reloading mid-game, and is two-fold.
- Setup that should only be done once can wind up being done each reload, as the `setupComplete` variable that is set to the return value of `doSetup()` does not persist across saves and reloads, so if an aspect is moved within the player area after a reload, `doSetup()` runs again.
- Setup that must be redone each time you reload (like setting the timer for Deep Slumber) *does not* automatically rerun each time you save and reload.

Both of these can be solved with code within the aspects (or other Setup requiring objects). Indeed, both have been solved within the mod already. Serpent's Deep Slumber object has special `onSave()` and `onLoad()` functions to restart its timer, and Immense and Sunshine solve the problem two different ways: Sunshine by not giving you the energy if it can't find Boon of Vigour to forget, and Immense by setting a flag in Lightning's `script_state`. Personally, I've solved the former issue in the general case by saving and restoring the `setupComplete` variable as part of the aspect's `script_state`. However, all the relevant code needs to be duplicated, and writing it requires a fair bit of understanding of TTS saving and loading, which seems very non-obvious to beginner modders.

To me, this suggests that `doSetup()` is serving two entirely different purposes: setup that should be done once at the start of the game, and setup that needs to be redone on every load, and that the current implementation is not ideally suited to either of them. Setting an option as to which it is doesn't work, as Serpent clearly needs a bit of both (immediately set up the snap points, each time start the timer). Which suggests to me that the solution is to split it in two: `doInitialSetup()` and `doRecurringSetup()` (except with better names). Each would need its own replacement for the `Setup` tag. The two would work similarly to the existing `doSetup()`, with the following differences:
- `doInitialSetup()` would set an `initialSetupComplete` variable, and this variable would be automatically baked by the main mod into the script state of the relevant object when `doInitialSetup()` returns, preventing it from rerunning on save-and-reload.
- `doRecurringSetup()` would set the `recurringSetupComplete` variable, which, like the current `setupComplete` variable, would not be saved anywhere, and would not persist through reloads. However, it would also set some variable (like Deep Slumber's) `initialised` variable, that is saved in `script_state`, and indicates that `doRecurringSetup` should be immediately rerun on loading the whole mod. The code to call `doRecurringSetup()` again in this situation would live in the global mod, again removing code from each object.

On the whole, this change should make things simpler to perform automation for new (NI or custom) aspects, as well as reducing code duplication within aspects and other objects with setup automation.

If desired, backwards compatibility could be maintained by leaving in the existing `Setup` tag, `doSetup()` function, and `setupComplete` variables as they are.

I'm very happy to write all the code for this myself (as well as changing Deep Slumber, Days That Never Were, Sunshine, Immense, etc. to match) and submit a PR. However, before going to the effort of doing so, I wanted to ask whether this is a good idea that has a chance of being incorporated, and to solicit feedback on the names (I don't particularly like `initial` and `recurring`).

### PR DESCRIPTION
**Pull request by pyrrhicPachyderm**
Fix #113.
This could occur if the objects were picked up a moved within the player area. This was because the setupComplete variable was stored in a way that did not persist across save/reload. Store it in script state instead to fix that. This also require slight changes to Deep Slumber, Pour Down Power Across the Island, and Ocean's Drowning bag, to prevent their onSave() functions overwriting the script state.

### CODE REVIEW

File: script.lua [hunk 1]
```diff
@@ -3639,9 +3647,18 @@ function runSpiritSetup()
...
+                    -- Whether the object has already done setup is stored in its script state, to persist across save/reload
+                    local json = JSON.decode(obj.script_state)
+                    if not json then
+                        json = {}
+                    end
+                    if not json.setupComplete then
+                        local success = obj.call("doSetup", {color=color})
+                        json.setupComplete = success
+                        obj.script_state = JSON.encode(json)
+                        break
```
Comment (iakona) [inline script.lua:3660]: i'm not seeing this break exist before the change, so i think adding it would be a bug. in theory a spirit could have multiple objects in their play area that need setup

Comment (pyrrhicPachyderm) [reply script.lua:3660]: Ah, you're absolutely right. That's a result of copying the code over from `onObjectEnterScriptingZone()`. It feels like there's a fair bit of code duplication in the parts of these two functions that run `doSetup` on objects, but they're different enough that I couldn't find an elegant way of removing the duplication. I'll just knock out the break for now; that should fix it.

**Comment by iakona** [comment]
while not necessary, do you think Immense Lighting (and by proxy Spreading Hostility Keeper) need to set a script state variable on the spirit board since it should be covered now by `setupComplete`?

**Comment by pyrrhicPachyderm** [comment]
No, that's probably not necessary any more. The only case in which I think it would be relevant is if someone copy-pastes the Immense object. In which case, just relying on `setupComplete` and not on Lightning's script state could allow the energy track to get doubled twice. But that seems a very niche problem; up to you whether you think avoiding that is worth leaving that code in.
