### PR TITLE
Fix discarding the wrong player's powers when picking.

### LINKED ISSUE #150: Picking a power in front of another player discards your cards.
If another player has a set of power cards to gain in front of them, and you left-click one, it discards the power cards in front of you (if you have any) instead of the ones in front of them.

This is a two-fold issue. The fact that it discards the cards in front of you is clearly not desirable behaviour. Whether or not it's desirable that it *doesn't* discard the cards in front them is debatable. However, I argue that is desirable that it would discard them.

I see this arising (choosing cards in front of another player) in two contexts: Entwined Power, and mistakes in multi-handed play.
- In Entwined Power, the target of Entwined Power is usually the player to click the "Gain a Major" or "Gain a Minor" button, and thus has the cards in front of them. If resolving the power gains in the order on Entwined Power, the target spirit would first choose a card (right-clicking), then the spirit who played the power. When the spirit who played the power gains a card, it doesn't discard the remaining cards. This forces the player of the target spirit to then gain one more card and forget it from hand, to make the discard. In practice, often the target declares which card they want but doesn't choose it yet, then the spirit who played the power chooses a different card, then the target chooses a card and things are discard properly, but this is still very awkward. If spare powers were discarded even when a power was chosen by a different spirit, this could all flow quite naturally in the order printed on the card.
- In multi-handed play, I often forget to switch spirits before gaining a power for a spirit. This deals the powers in front of the the wrong spirit. If I *then* switch seats to the correct spirit (so it gains the power to the correct hand), then it doesn't discard the powers when I gain them.

Changing it so that it does discard powers when a different spirit gains them would be a change from a behaviour that some players are now used to, so could cause a few problems in adjustment, but I believe it's worth it to make things flow more smoothly in general.

### PR DESCRIPTION
**Pull request by pyrrhicPachyderm**
Fix #150.

This has it discard powers when gaining powers from in front of another spirit, as I argued for in #150, but I can change that to just fix the unintentional discards if you disagree with me.

### CODE REVIEW

File: script.lua [hunk 1]
```diff
@@ -2228,15 +2228,32 @@ function PickPower(cardo,playero,alt_click)
     if cardo.hasTag("Major") then
         Player[playero].broadcast("Don't forget to Forget a Power Card!", Color.SoftYellow)
     end
-    -- Give card to player regardless of whose hand they are in front of
+    -- Figure out which player the card is in front of
+    local handPos = nil
+    for color,_ in pairs(playerTables) do
```
Comment (iakona) [inline script.lua:2233]: for iterating through a list of colors `selectedColors` has how i've typically been handling that

**Comment by iakona** [comment]
also i'm fine with discard powers in front of other players, reading through the flow of entwined power makes sense

File: script.lua (hunk 1 above)
Comment (pyrrhicPachyderm) [reply script.lua:2233]: I went with `playerTables` instead of `selectedColors` because all the power gain functionality still works even for a player who's picked a seat but not a spirit, in which case they appear in `playerTables` but not `selectedColors`. Sure, people probably *shouldn't* be gaining power cards before picking a spirit, but they *can* do, and it seems better to make it robust in case they do.

Comment (iakona) [reply script.lua:2233]: interesting, fair point
